# Netlify configuration for Angular SPA
[build]
  # Build command (if needed)
  command = "npm run build"
  # Directory to publish - MUST MATCH angular.json outputPath
  publish = "dist/notificador-sunat-front"

# Redirect rules for Angular routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Optional: Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
